### ISSUE TITLE
Incompatible with recent stable mkdocs 1.1

### ISSUE THREAD

**Issue by Voronenko** [midnightprioriem/mkdocs-toc-sidebar-plugin#3]
Starting from latest release 1.1 mkdocs has dropped support for py2, and thus it no longer has definition for string_types , etc used in plugin configuration

**Comment by 1300371** [comment]
I think this is same kind of issue:
```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 140, in serve_command
    serve.serve(
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 141, in serve
    config = builder()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 122, in builder
    config = load_config(
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 197, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 107, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 62, in _validate
    self[key] = config_option.validate(value)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 130, in validate
    return self.run_validation(value)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 591, in run_validation
    plgins[item] = self.load_plugin(item, cfg)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 599, in load_plugin
    Plugin = self.installed_plugins[name].load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2444, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/mkdocs_toc_sidebar_plugin/plugin.py", line 14, in <module>
    class TocSidebar(BasePlugin):
  File "/usr/local/lib/python3.8/site-packages/mkdocs_toc_sidebar_plugin/plugin.py", line 17, in TocSidebar
    ('param', config_options.Type(mkdocs_utils.string_types, default='')),
AttributeError: module 'mkdocs.utils' has no attribute 'string_types'
```
